name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Generate-Winget-Pkgs-Db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout Microsoft Repo
        uses: actions/checkout@v4
        with:
          repository: "microsoft/winget-pkgs"
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install Dependencies
        run: "pip3 install -r requirements.txt"
      - name: Export Winget Database
        run: "python3 main.py"

      - name: Archive Database
        uses: actions/upload-artifact@v4
        with:
          name: winget-pkg-db.db
          path: ${{ github.workspace }}/winget-pkg-app.db
  Deploy-Cloudflare-Pages:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    needs: Generate-Winget-Pkgs-Db
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: winget-pkg-db.db
          path: ${{ github.workspace }}/frontend/
      - name: Check Directory
        run: ls frontend
      - name: Build
        run: cd frontend && (curl -fsSL https://deno.land/x/install/install.sh | sh && /home/runner/.deno/bin/deno task build)
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: arm-ready-windows # e.g. 'my-project'
          directory: ${{ github.workspace }}/frontend/_site # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
